const express = require('express');
const fs = require('fs');
const path = require('path');
const { scoreChoice, scoreAime, aggregateScore } = require('./server/scoring');
const app = express();
app.use(express.json({limit:'2mb'}));
app.use(express.static(path.join(__dirname,'dist')));
app.use(express.static(path.join(__dirname,'public')));
const runs = new Map();
function normalizeRunScores(run){for(const row of run.rows||[]){const a=row.average;if(a&&Number.isFinite(a.correct)&&Number.isFinite(a.total)&&(Number.isFinite(a.unknown)||a.unknown===0))a.score=a.total>0?a.correct/a.total:0;for(const detail of row.details||[]){if(detail&&Number.isFinite(detail.correct)&&Number.isFinite(detail.total)&&(Number.isFinite(detail.unknown)||detail.unknown===0))detail.score=detail.total>0?detail.correct/detail.total:0;}}return run;}
try { const savedRuns = path.join(__dirname,'data','runs.json'); if (fs.existsSync(savedRuns)) for (const r of JSON.parse(fs.readFileSync(savedRuns,'utf8'))) runs.set(r.id,normalizeRunScores(r)); } catch {}
function saveRuns(){ fs.mkdirSync(path.join(__dirname,'data'),{recursive:true}); fs.writeFileSync(path.join(__dirname,'data','runs.json'), JSON.stringify([...runs.values()],null,2)); }
const controllers = new Map();
const dataDir = path.join(__dirname,'scripts','data');
const stateFile = path.join(__dirname, 'data', 'workbench-state.json');
let state = { profiles: [], models: [], comparisons: [], baselines: [] };
try { if (fs.existsSync(stateFile)) state = JSON.parse(fs.readFileSync(stateFile, 'utf8')); } catch {}
function saveState(){ fs.mkdirSync(path.dirname(stateFile), {recursive:true}); fs.writeFileSync(stateFile, JSON.stringify(state,null,2)); }
const tasks = [
  {id:'smoke_speed',name:'连通性与吐字速度',ability:'实际可用性 / 首 token 与生成速度',kind:'smoke'},
  {id:'gpqa_cached',name:'GPQA Diamond（缓存题库）',ability:'高难度科学推理与知识整合',kind:'gpqa',file:'gpqa_diamond_mc.jsonl'},
  {id:'aime_cached',name:'AIME 2025（缓存题库）',ability:'数学竞赛推理与精确计算',kind:'aime',file:'aime_2025.jsonl'},
  {id:'mmlu_pro_cached',name:'MMLU-Pro（缓存题库）',ability:'广泛知识、学科理解与选择题稳健性',kind:'mmlu',file:'MMLU-Pro.jsonl'}
];
app.get('/api/tasks',(req,res)=>res.json(tasks));
app.get('/api/catalog',(req,res)=>res.json({protocolVersion:'1.0',manifests:tasks.map(t=>({...t,version:'1.0',supports:['standard','exploration']}))}));
app.get('/api/preflight',(req,res)=>{const docker=process.env.WSL2_DOCKER==='1'; const wsl2=process.platform==='linux' || !!process.env.WSL_DISTRO_NAME; res.json({ok:true,platform:process.platform,wsl2,docker,dynamicIsolation:docker&&wsl2,checkedAt:new Date().toISOString()});});
function publicProfile(profile){const {key,...safe}=profile||{}; return {...safe,hasKey:Boolean(key)};}
app.get('/api/profiles',(req,res)=>res.json({profiles:state.profiles.map(publicProfile),models:state.models}));
app.post('/api/profiles',(req,res)=>{const p={...req.body,id:req.body.id||'default',updatedAt:new Date().toISOString()}; if(!req.body.rememberKey) delete p.key; const i=state.profiles.findIndex(x=>x.id===p.id); if(i>=0)state.profiles[i]=p; else state.profiles.push(p); if(Array.isArray(p.models))state.models=p.models; saveState(); res.json(publicProfile(p));});
app.get('/api/comparisons',(req,res)=>res.json(state.comparisons));
app.post('/api/comparisons',(req,res)=>{const c={...req.body,id:req.body.id||Date.now().toString(36),createdAt:new Date().toISOString()}; state.comparisons.push(c); saveState(); res.status(201).json(c);});
app.patch('/api/comparisons/:id',(req,res)=>{const c=state.comparisons.find(x=>x.id===req.params.id); if(!c)return res.status(404).json({error:'not found'}); Object.assign(c,req.body, {updatedAt:new Date().toISOString()}); saveState(); res.json(c);});
app.post('/api/models',async(req,res)=>{try{const c=req.body||{}, base=(c.endpoint||'http://127.0.0.1:9292/v1').replace(/\/$/,''); const r=await fetch(base+'/models',{headers:c.key?{Authorization:'Bearer '+c.key}:{}}); if(!r.ok) throw Error('HTTP '+r.status); res.json(await r.json());}catch(e){res.status(502).json({error:e.message})}});
app.get('/api/results',(req,res)=>res.json([...runs.values()].filter(x=>x.status!=='running').reverse().map(run=>({...run,rows:(run.rows||[]).map(row=>({...row,log:(row.log&&row.log.length)?row.log:(run.log||[])}))}))));
app.get('/api/runs/:id',(req,res)=>res.json(runs.get(req.params.id)||{error:'not found'}));
app.delete('/api/runs/:id',(req,res)=>{const run=runs.get(req.params.id);if(!run)return res.status(404).json({error:'not found'});run.cancelRequested=true;run.current='正在中断…';const c=controllers.get(run.id);if(c)c.abort();saveRuns();res.json({ok:true});});
app.post('/api/runs',async(req,res)=>{const b=req.body||{}, models=Array.isArray(b.models)?b.models.filter(Boolean):[], selected=Array.isArray(b.tasks)?b.tasks.filter(Boolean):[]; if(!models.length||!selected.length)return res.status(400).json({error:'至少选择一个模型和一个测试项目'}); const dynamic=selected.some(x=>/ctf|red|blue|terminal|code/i.test(x)); if(dynamic && process.env.WSL2_DOCKER!=='1') return res.status(422).json({error:'动态代码/终端/CTF协议需要 WSL2 Docker 隔离环境',code:'unsupported',preflight:{docker:false,wsl2:false}}); const id=Date.now().toString(36); const run={id,name:b.name||'未命名测试',alias:b.alias||b.name||'未命名测试',note:b.note||'',models,tasks:selected,repeats:Math.min(20,Math.max(1,Number(b.repeats)||1)),concurrency:Math.min(16,Math.max(1,Number(b.concurrency)||1)),status:'running',startedAt:new Date().toISOString(),rows:[],log:[],errors:[],progress:{modelIndex:0,taskIndex:0,repeat:0,total:models.length*selected.length},config:{depth:b.depth,category:b.category,difficulty:b.difficulty,contextTarget:b.contextTarget,seed:b.seed}}; runs.set(id,run); res.status(202).json({id}); execute(run,b).catch(e=>{run.status=run.rows.length?'crashed':'error';run.errors.push(e.stack||e.message);run.log.push('运行级错误：'+(e.stack||e.message));run.finishedAt=new Date().toISOString()});});
async function execute(run,b){for(let mi=0;mi<run.models.length&&!run.cancelRequested;mi++){const model=run.models[mi];run.progress.modelIndex=mi;for(let ti=0;ti<run.tasks.length&&!run.cancelRequested;ti++){const taskId=run.tasks[ti],task=tasks.find(t=>t.id===taskId);run.progress.taskIndex=ti;run.current=`${model} · ${task?.name||taskId} · 并发 ${run.concurrency}`;if(!task){run.errors.push(`未知测试项目：${taskId}`);continue} const vals=[],entryLog=[],jobs=Array.from({length:run.repeats},(_,i)=>i);let cursor=0;async function worker(){while(cursor<jobs.length&&!run.cancelRequested){const i=jobs[cursor++],startLine=`${model} / ${task.name} / 第 ${i+1} 次：请求中…`;run.progress.repeat=i+1;entryLog[i]=startLine;run.log.push(startLine);try{const v=await measure(run,b,model,task);if(run.cancelRequested)break;vals[i]=v;const line=`${model} / ${task.name} / 第 ${i+1} 次：${JSON.stringify(v)}`;entryLog[i]=line;run.log.push(line)}catch(e){if(run.cancelRequested)break;const msg=`${model} / ${task.name} / 第 ${i+1} 次失败：${e.message}`;run.errors.push(msg);entryLog[i]=msg;run.log.push(msg)}}} await Promise.all(Array.from({length:Math.min(run.concurrency,jobs.length)},worker));const good=vals.filter(Boolean);const avg={};if(good.length){for(const k of Object.keys(good[0])){if(typeof good[0][k]==='number')avg[k]=good.reduce((s,x)=>s+(x[k]||0),0)/good.length;else avg[k]=good[good.length-1][k]}}else{avg.score=0;avg.correct=0;avg.total=run.repeats}run.rows.push({model,task:task.name,ability:task.ability,repeat:good.length,average:avg,details:good,log:entryLog.filter(Boolean)}); saveRuns();}}run.current=run.cancelRequested?'已中断（已保留部分结果）':'已完成';run.status=run.cancelRequested?'partial':(run.errors.length?'error':'done');run.finishedAt=new Date().toISOString(); saveRuns();}
async function measure(run,b,model,task){if(task.kind==='smoke'){const t=Date.now(); const r=await chat(b,model,'请只回复：测试通过。',{max_tokens:64,runId:run.id}); const ms=Date.now()-t; return {ok:1,firstMs:ms,tokens:r.tokens||0,tokPerSec:r.tokPerSec||0,output:r.text.slice(0,80)}} const lines=fs.readFileSync(path.join(dataDir,task.file),'utf8').trim().split(/\r?\n/); const requested=Number(b.limit); const count=Number.isFinite(requested)&&requested>0?Math.min(requested,lines.length):lines.length; const sample=lines.slice(0,count).map(JSON.parse); let correct=0,total=0; for(let qi=0;qi<sample.length&&!run.cancelRequested;qi++){const q=sample[qi];let prompt=''; if(task.kind==='gpqa')prompt=`请解答下面选择题。最后一行必须严格写成“最终答案：X”，X只能是 A、B、C 或 D。\n${q.problem}`; else if(task.kind==='aime')prompt=`请解答下面AIME数学题。最后一行必须严格写成“最终答案：N”，N是0到999的整数。\n${q.problem}`; else prompt=`请解答下面选择题。最后一行必须严格写成“最终答案：X”，X只能是 A-J。\n${q.question}\n${q.options_text}`; run.log.push(`${model} / ${task.name} / 题目 ${qi+1}/${count}：请求中…`); const r=await chat(b,model,prompt,{max_tokens:1024,runId:run.id}); const raw=(r.text||'').trim(); const answerText=raw||'[content为空；可能只有reasoning或达到长度上限]'; let ans=''; const marked=answerText.match(/最终答案\s*[：:]\s*([A-J])/i)||answerText.match(/\\boxed\{\\s*([A-J])\\s*\\}/i); if(marked)ans=marked[1].toUpperCase(); else ans=(answerText.match(/[A-J](?!.*[A-J])/i)||[''])[0].toUpperCase(); const expected=task.kind==='gpqa'?q.answer.toUpperCase():task.kind==='mmlu'?String(q.answer).toUpperCase():String(q.answer); const ok=task.kind==='gpqa'||task.kind==='mmlu'?ans===expected:(answerText.match(/\b\d{1,3}\b/g)||[]).slice(-1)[0]===expected; if(ok)correct++;total++; run.log.push(`${model} / ${task.name} / 题目 ${qi+1}/${count}：${ok?'正确':'错误'}，模型回答 ${answerText.slice(0,240)}`);} return {score:total?correct/total:0,correct,total,samples:count};}
async function chat(b,model,prompt,opts){const base=(b.endpoint||'http://127.0.0.1:9292/v1').replace(/\/$/,''); const headers={'Content-Type':'application/json'};if(b.key)headers.Authorization='Bearer '+b.key; const t=Date.now(); const controller=new AbortController();controllers.set(opts.runId||'',controller); let r;try{r=await fetch(base+'/chat/completions',{method:'POST',headers,body:JSON.stringify({model,messages:[{role:'user',content:prompt}],temperature:0,max_tokens:opts.max_tokens||128,stream:false,chat_template_kwargs:{enable_thinking:false}}),signal:controller.signal})}finally{controllers.delete(opts.runId||'')}if(!r.ok)throw Error('HTTP '+r.status+' '+await r.text()); const j=await r.json(); const msg=j.choices?.[0]?.message||{}; const text=msg.content||''; const usage=j.usage||{}; const tok=usage.completion_tokens||text.length/2; return {text,tokens:tok,tokPerSec:tok/Math.max(.001,(Date.now()-t)/1000),finishReason:j.choices?.[0]?.finish_reason,raw:j};}
// The scorer is deliberately strict: reasoning without final-answer evidence is unknown, never incorrect.
async function measure(run,b,model,task){
  if(task.kind==='smoke'){const t=Date.now();const r=await chat(b,model,'请只回复：测试通过。',{max_tokens:64,runId:run.id});const ms=Date.now()-t;return {ok:1,firstMs:ms,tokens:r.tokens||0,tokPerSec:r.tokPerSec||0,output:r.text.slice(0,80)}}
  const lines=fs.readFileSync(path.join(dataDir,task.file),'utf8').trim().split(/\r?\n/);
  const requested=Number(b.limit);const count=Number.isFinite(requested)&&requested>0?Math.min(requested,lines.length):lines.length;const sample=lines.slice(0,count).map(JSON.parse);let correct=0,incorrect=0,unknown=0;
  for(let qi=0;qi<sample.length&&!run.cancelRequested;qi++){
    const q=sample[qi];let prompt='';
    if(task.kind==='gpqa')prompt=`请解答下面选择题。最后一行必须严格写成“最终答案：X”或“\\boxed{X}”，X只能是 A、B、C 或 D。\n${q.problem}`;
    else if(task.kind==='aime')prompt=`请解答下面AIME数学题。最后一行必须严格写成“最终答案：N”或“\\boxed{N}”，N是0到999的整数。\n${q.problem}`;
    else prompt=`请解答下面选择题。最后一行必须严格写成“最终答案：X”或“\\boxed{X}”，X只能是 A-J。\n${q.question}\n${q.options_text}`;
    run.log.push(`${model} / ${task.name} / 题目 ${qi+1}/${count}：请求中…`);
    const outputLimit=Math.min(8192,Math.max(256,Number(b.maxTokens)||4096));const r=await chat(b,model,prompt,{max_tokens:outputLimit,runId:run.id});const answerText=(r.text||r.reasoningText||'').trim();
    const expected=task.kind==='aime'?String(q.answer):String(q.answer||'').toUpperCase();
    const verdict=task.kind==='aime'?scoreAime(expected,answerText):scoreChoice(expected,answerText);
    if(verdict.status==='correct')correct++;else if(verdict.status==='incorrect')incorrect++;else unknown++;
    const verdictLabel=verdict.status==='unknown'?(r.finishReason==='length'?'未知（输出达到长度上限）':'未知（没有明确最终答案）'):verdict.status==='correct'?'正确':'错误';run.log.push(`${model} / ${task.name} / 题目 ${qi+1}/${count}：${verdictLabel}，模型回答 ${answerText}`);
  }
  const answered=correct+incorrect;return {score:aggregateScore({correct,incorrect,unknown,total:count}),correct,incorrect,unknown,total:count,answered,samples:count};
}

async function chat(b,model,prompt,opts){const base=(b.endpoint||'http://127.0.0.1:9292/v1').replace(/\/$/,'');const headers={'Content-Type':'application/json'};if(b.key)headers.Authorization='Bearer '+b.key;const t=Date.now();const controller=new AbortController();controllers.set(opts.runId||'',controller);let r;try{r=await fetch(base+'/chat/completions',{method:'POST',headers,body:JSON.stringify({model,messages:[{role:'user',content:prompt}],temperature:0,max_tokens:opts.max_tokens||128,stream:false,chat_template_kwargs:{enable_thinking:false}}),signal:controller.signal})}finally{controllers.delete(opts.runId||'')}if(!r.ok)throw Error('HTTP '+r.status+' '+await r.text());const j=await r.json();const msg=j.choices?.[0]?.message||{};const text=msg.content||'';const reasoningText=msg.reasoning_content||msg.reasoning||'';const usage=j.usage||{};const tok=usage.completion_tokens||text.length/2;return {text,reasoningText,tokens:tok,tokPerSec:tok/Math.max(.001,(Date.now()-t)/1000),finishReason:j.choices?.[0]?.finish_reason,raw:j};}

app.listen(process.env.PORT||3000,()=>console.log('llm-test listening on '+(process.env.PORT||3000)));

